import { build } from 'esbuild';

import { readFile, mkdir, rm } from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('.sites-runtime/tests',{recursive:true});
await build({stdin:{contents:'export {handleApi} from "./lib/api"; export {database,closeDatabase} from "./db"',resolveDir:process.cwd()},outfile:'.sites-runtime/tests/worker.mjs',bundle:true,format:'esm',platform:'node',packages:'external'});
await build({entryPoints:['lib/core.ts'],outfile:'.sites-runtime/tests/core.mjs',bundle:true,format:'esm',platform:'node'});
const {normalize,candidateMatches,exactDevice,validImei}=await import('../.sites-runtime/tests/core.mjs');
assert.notEqual(normalize('Samsung Galaxy S23+'),normalize('Samsung Galaxy S23'));
assert.equal(candidateMatches('File:Galaxy S23 Ultra.png','Samsung Galaxy S23 Ultra'),true);
assert.equal(candidateMatches('File:Galaxy S23 Ultra.png','Samsung Galaxy S23'),false);
assert.equal(candidateMatches('File:Galaxy S23.png','Samsung Galaxy S23+'),false);
assert.equal(candidateMatches('File:IPhone 15 and iPhone 14.jpg','iPhone 15'),false);
assert.equal(exactDevice([['Accent','PEARL A6','','ABC'],['Accent','Pearl A6','','ABC']],'ABC'),'Accent Pearl A6');
assert.equal(validImei('490154203237518'),true);
assert.equal(validImei('490154203237519'),false);
console.log('PASS model variant matching, CSV deduplication, and IMEI validation');
let sourceRequests=0;
const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=','base64');
const testDb=`.sites-runtime/tests/test-${process.pid}.db`;
Object.assign(process.env,{TURSO_DATABASE_URL:`file:${testDb}`,ADMIN_PASSWORD:'integration-test-password-only',SESSION_SECRET:'integration-test-session-secret-at-least-32',CORS_ORIGIN:'https://client.example'});
const {handleApi,database,closeDatabase}=await import('../.sites-runtime/tests/worker.mjs');
const originalFetch=globalThis.fetch;
globalThis.fetch=async(input,init)=>{const request=new Request(input,init);
  sourceRequests++;
  const url=new URL(request.url);
  if(url.hostname==='storage.googleapis.com') return new Response(Buffer.from('\ufeffRetail Branding,Marketing Name,Device,Model\r\nSamsung,Galaxy S23 Ultra,dm3q,SM-S918B\r\n','utf16le'),{headers:{'content-type':'text/csv;charset=utf-16le'}});
  if(url.pathname.includes('Category:Samsung_Galaxy_S23_Ultra')) return new Response('<div class="gallerybox"><a href="/wiki/File:Galaxy_S23_Ultra.png">image</a></div>',{headers:{'content-type':'text/html'}});
  if(url.pathname.includes('File:Galaxy_S23_Ultra.png')) return new Response('<html><div class="fullImageLink"><img src="https://upload.wikimedia.org/test.png"></div><table><tr><td id="fileinfotpl_aut">Author</td><td><a>Fixture Photographer</a></td></tr></table><div class="licensetpl"><span class="licensetpl_short">CC BY-SA 4.0</span><span class="licensetpl_link">https://creativecommons.org/licenses/by-sa/4.0/</span><span class="licensetpl_nonfree">false</span></div></html>',{headers:{'content-type':'text/html'}});
  if(url.hostname==='upload.wikimedia.org')return new Response(image,{headers:{'content-type':'image/png'}});
  if(url.pathname.includes('Outage'))return new Response('Temporarily unavailable',{status:503});
  return new Response('Missing',{status:404});
};
const mf={getD1Database:async()=>database(),dispatchFetch:(url,init)=>handleApi(new Request(url,init)),dispose:async()=>{globalThis.fetch=originalFetch;closeDatabase();await rm(testDb,{force:true});}};
try{
  const db=await mf.getD1Database('DB');
  const migration=await readFile('drizzle/0000_productive_namor.sql','utf8');
  for(const statement of migration.split('--> statement-breakpoint').map(x=>x.trim()).filter(Boolean)) await db.prepare(statement).run();
  let cookie='';
  async function req(path,method='GET',body,headers={}){return mf.dispatchFetch('https://test.example'+path,{method,headers:{...(cookie?{cookie}:{}),...(body?{'content-type':'application/json',origin:'https://test.example'}:{}),...headers},body:body?JSON.stringify(body):undefined});}
  let r=await req('/api/v1/image?model=SM-S918B');assert.equal(r.status,401);
  r=await req('/api/admin/login','POST',{password:'wrong'});assert.equal(r.status,401);
  r=await req('/api/admin/login','POST',{password:'integration-test-password-only'});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly/);cookie=r.headers.get('set-cookie').split(';')[0];
  r=await req('/api/admin/keys','POST',{name:'Test application'});assert.equal(r.status,201);const key=await r.json();assert.match(key.key,/^isk_/);
  r=await req('/api/admin/aliases','POST',{alias:'SM-S918B',name:'Samsung Galaxy S23 Ultra'},{origin:'https://evil.example'});assert.equal(r.status,403);
  const adminCookie=cookie;cookie='';
  const bearer={authorization:`Bearer ${key.key}`};
  r=await req('/api/v1/image?model=SM-S918B','GET',undefined,bearer);
  const first=await r.json();assert.equal(r.status,200,JSON.stringify(first));assert.equal(first.cached,false);assert.equal(first.model,'Samsung Galaxy S23 Ultra');assert.equal(first.attribution,'Fixture Photographer');assert.equal(first.license,'CC BY-SA 4.0');
  const sourceAfterFirst=sourceRequests;
  r=await req('/api/v1/image?model=sm-s918b','GET',undefined,bearer);assert.equal((await r.json()).cached,true);assert.equal(sourceRequests,sourceAfterFirst);
  r=await req('/api/v1/image?model=samsung%20galaxy%20s23%20ultra','GET',undefined,bearer);assert.equal((await r.json()).cached,true);assert.equal(sourceRequests,sourceAfterFirst);
  r=await req(new URL(first.image_url).pathname,'GET',undefined,bearer);assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await r.arrayBuffer()),image);
  const etag=r.headers.get('etag');r=await req(new URL(first.image_url).pathname,'GET',undefined,{...bearer,'if-none-match':etag});assert.equal(r.status,304);
  r=await req('/api/v1/image?model=Unknown%20Device','GET',undefined,bearer);assert.equal(r.status,404);const afterMiss=sourceRequests;r=await req('/api/v1/image?model=Unknown%20Device','GET',undefined,bearer);assert.equal(r.status,404);assert.equal(sourceRequests,afterMiss);
  r=await req('/api/v1/image?model=Outage','GET',undefined,bearer);assert.equal(r.status,502);assert.equal((await db.prepare("SELECT count(*) AS n FROM misses WHERE query='outage'").first()).n,0);
  r=await req('/api/v1/imei','POST',{imei:'490154203237519'},bearer);assert.equal(r.status,400);
  r=await req('/api/v1/imei','POST',{imei:'490154203237518'},bearer);assert.equal(r.status,422);
  cookie=adminCookie;r=await req('/api/admin/tacs','POST',{tac:'49015420',name:'Samsung Galaxy S23 Ultra'});assert.equal(r.status,201);cookie='';
  r=await req('/api/v1/imei','POST',{imei:'490154203237518'},bearer);assert.equal(r.status,200);assert.equal((await r.json()).cached,true);
  r=await req('/api/v1/image?model=SM-S918B','OPTIONS',undefined,{origin:'https://client.example'});assert.equal(r.headers.get('access-control-allow-origin'),'https://client.example');
  cookie=adminCookie;r=await req('/api/admin/overview');assert.equal(r.status,200);const overview=await r.json();assert.equal(overview.stats.models,1);assert.equal(overview.keys.length,1);assert.equal(overview.tacs.length,1);
  r=await req('/api/admin/models?search=Galaxy&page=1');assert.equal(r.status,200);assert.equal((await r.json()).total,1);
  r=await req('/api/admin/models/samsung%20galaxy%20s23%20ultra','PATCH',undefined,{origin:'https://test.example'});assert.equal(r.status,200);
  r=await req(`/api/admin/keys/${key.id}`,'DELETE',undefined,{origin:'https://test.example'});assert.equal(r.status,200);cookie='';r=await req('/api/v1/image?model=SM-S918B','GET',undefined,bearer);assert.equal(r.status,401);
  cookie=adminCookie;r=await req('/api/admin/models/samsung%20galaxy%20s23%20ultra','DELETE',undefined,{origin:'https://test.example'});assert.equal(r.status,200);r=await req('/api/admin/overview');assert.equal((await r.json()).stats.models,0);
  console.log('PASS login, CSRF, API keys, bundled Google model resolution, Commons HTML scraping, attribution, BLOB persistence, cache hits, conditional images, negative cache, source errors, IMEI/TAC, CORS, search, review, revoke and delete');
}finally{await mf.dispose();}
